### ISSUE TITLE
Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by forki** [Krzysztof-Cieslak/FSharp.Atom#19]
![atom](https://cloud.githubusercontent.com/assets/57396/7473201/9fca8778-f339-11e4-8b44-94e54be848a4.png)

any ideas?

**Comment by Krzysztof-Cieslak** [comment]
Fix: Open folder 'src/core/' with Atom and run "Update Package Dependencies" from Atom command palette. Same for 'src/paket' folder. 

Problem: I don't upload to GitHub node_modules folders which contains NPM dependencies for packages.  

If I understand correctly, those dependencies would be installed during Atom package installation process If download through APM. But we are not using it yet, and even if we were, for development purpose calling "Update Package Dependencies" from Atom command palette whenever NPM dependencies changes is necessery

**Comment by forki** [comment]
thanks.

**Comment by Krzysztof-Cieslak** [comment]
Actually, I think it would be a good idea to include installing those dependencies in our build - we should run `npm install` in all (at the moment 2) folders with package.json in our FAKE build file

**Comment by forki** [comment]
project moved to https://github.com/fsprojects/Paket.Atom and new discussion is at https://github.com/fsprojects/Paket.Atom/issues/9
