### ISSUE TITLE
Does it build?

### ISSUE THREAD

**Issue by tpetricek** [Krzysztof-Cieslak/FSharp.Atom#4]
I tried getting the latest version and building it from the source using `build.cmd`. I get exactly the same error that @Krzysztof-Cieslak was getting earlier. The output is:

    No version specified. Downloading latest stable.
    Paket.exe 0.37.0.0 is up to date.
    Paket version 0.37.0.0
    1 second - ready.

    F# Interactive for F# 3.1 (private)
    Freely distributed under the Apache 2.0 Open Source License

    For help type #help;;

    > [Loading c:\Tomas\Public\FSharp.Atom\src\core.fsx
     Loading c:\Tomas\Public\FSharp.Atom\src\funscript-atom.fsx
     Loading c:\Tomas\Public\FSharp.Atom\src\atom-bindings.fsx
     Loading c:\Tomas\Public\FSharp.Atom\src\paket.fsx
     Loading c:\Tomas\Public\FSharp.Atom\build.fsx]

    src\core.fsx(15,6): error FS0039: The namespace or module 'Atom' is not defined

I also see this error when I open `build.fsx` (on the line that `#load`s `src/core.fsx`), but when I open `core.fsx`, the error is not there (if I ignore it, it runs fine in F# Interactive). Am I the only one seeing this?

I do not understand why FAKE would be showing F# Interactive output - as far as I remember, it did not used to do this (I guess since it started using F# Interactive Service?) (cc @forki)

This might also have something to do with what versions of F#/Visual Studio you have installed. I was not getting this error before, but I had both F# Core 3.0 and 3.1 in GAC. Now I'm on a machine with just F# Core 3.1.

**Comment by Krzysztof-Cieslak** [comment]
So,

**Comment by tpetricek** [comment]
Yes, that's exactly the same behavior I got. But it *did* work on another machine! What versions of `FSharp.Core` do you have in GAC? (I have 4.3.1.0 and 2.3.0.0).

**Comment by Krzysztof-Cieslak** [comment]
![image](https://cloud.githubusercontent.com/assets/5427083/6883445/658a5fce-d5ad-11e4-8c70-2d05059445a8.png)

Well, Gacutil is showing even 3 versions of F# Core on my PC - 2.3.0.0, 4.3.0.0 and 4.3.1.0

**Comment by forki** [comment]
> I do not understand why FAKE would be showing F# Interactive output

I think there is/was a FCS issue about that. But can't find it because of @github DDoS. /cc @dsyme

**Comment by jwood803** [comment]
I got the same error as @tpetricek. When I load the solution in VS I see the below from `build.fsx`. 

![Core Error](https://dl.dropboxusercontent.com/s/d1kpn7iglxhmj4p/coreError.png?dl=0)

**Comment by rozgo** [comment]
![screen shot 2015-04-06 at 2 54 26 pm](https://cloud.githubusercontent.com/assets/92162/7012257/f377dc2e-dc6c-11e4-9c1b-2cc21e60c764.png)

This is what I get trying to generate bindings for: https://github.com/Krzysztof-Cieslak/FSharp.Atom/blob/master/typings/t.zip

Using fresh pull for FunScript. I have similar errors trying to generate bindings for latest blob from DefinitelyTyped.

**Comment by Krzysztof-Cieslak** [comment]
@rozgo, I've added Q definition to zip file.
Tomas noticed earlier that atom is on blacklist and I'm using my own FunScript.TypeScript.exe build with atom removed from blacklist.

I'm also using earlier version of JQuery definition file since FunScript doesn't support some newest TypeScript features - mostly union type in case of JQuery definition file.

**Comment by Krzysztof-Cieslak** [comment]
1. I had to change .net Framework version to 4.5 to make it compile on Windows and generate `FSharp.Atom.Generator.exe` file(https://github.com/Krzysztof-Cieslak/FSharp.Atom/commit/09ad8f1b525ff9d7b29ecbf97c536257c01573f8) 
2. If I run it from command line I get some unhandled exception from FunScript
![image](https://cloud.githubusercontent.com/assets/5427083/7101047/a8a3eb64-e042-11e4-90fb-aefe3f4deb1e.png) Building Generator works, problem is when script tries to execute it.
3. Running main.fs file from F# Interactive in VS works well
4. Running build.sh on Linux using mono works well

**Comment by tpetricek** [comment]
This typically happens because of missing binding redirects. I created the project in XamarinStudio, which provably doesn't create them by default (I think FunScript references different FSharp.Core than three EXE).
